### ISSUE TITLE
Abstract type member instantiation causes illegal cyclic reference compile error

### ISSUE THREAD

**Issue by odipar** [scala/bug#11560]
The following code doesn't compile and cause 'illegal cyclic reference' compile error
```scala
object IllegalCyclicReference {

  trait Problem {
    def x: X

    // If we uncomment below , we get the compiler error "illegal cyclic reference" ????
    // def z = x.z
  }

  trait Y[S]

  trait X {
    type S = Z

    trait Z extends Y[S]

    def z: Z
  }
}
```

See also ScalaFiddle: https://scalafiddle.io/sf/zuBKhBy/5

**Comment by odipar** [comment]
All major scala compiler (2.10, 2.11, 2.12) versions cause the error except Dotty.

**Comment by odipar** [comment]
I see the label 'fixed in Dotty' but is it really 'fixed'?

 It could well be that my construction is invalid and the none-Dotty compilers are correct...

**Comment by odipar** [comment]
non-Dotty == scala 2.x.y

**Comment by joroKr21** [comment]
That's awkward.
  * Moving `Problem` below `X` makes the error go away
  * So does ascribing `def z: X#S = x.z`
  * But ascribing `def z: X#Z = x.z` still fails

So I guess it depends on the order in which the types are completed.
