### ISSUE TITLE
Stack.popAll() return value is in wrong sequence!

### ISSUE THREAD

**Issue by sy20070** [scala/bug#12483]
## reproduction steps

using Scala 2.13.6 + AdoptOpenJDK 11

```scala
val stack1, stack2 = scala.collection.mutable.Stack.empty[Int]
stack1.push(1).push(2).push(3)
stack2.push(1).push(2).push(3)
println(stack1.popAll()) // print List(1, 2, 3)
println(stack2.popWhile(_ => true)) // print List(3, 2, 1)
```

## problem

The document of scala.collection.mutable.Stack said: 
> def popAll(): Seq[A]
Pop all elements from this stack and return it

As is known to all, for a stack, the "pop" means the element is removed from the top. 
For "pop all", I thought the result must be from the top to bottom. And `popWhile(_ => true)` and `popAll()` must be equivalent.
However the result shows `popAll()` is not expected.

If it is a correct behavior and I was in misunderstanding, I must say it is very confusing and the document must put a clear notice to users.

Thank you!

**Comment by som-snytt** [comment]
I see `popAll` is new for 2.13, so my guess is that the behavior is unintended.

Everywhere else, iteration order (pop order) is preserved. `popAll` and `popWhile` are unusual in returning `Seq` instead of `Stack`.

`Stack(1,2,3)` means top is `1`, not "construct a Stack by pushing 1 then 2 then 3". So "preserve iteration order" isn't documented and also isn't necessarily what you might assume, but it makes the operations easy to reason about.

**Comment by som-snytt** [comment]
It's also possible the collections team will send you a t-shirt for being the first customer to use `popAll`.

**Comment by sy20070** [comment]
The issue was resolved so quickly! Thanks for your efforts!

**Comment by som-snytt** [comment]
I think they will close the issue when or if they accept the PR. Then it's not really fixed until the next release.

Thanks for the report, it's an interesting lesson in API design.
