### ISSUE TITLE
Future not completed and onFailure not called when OOM or InterruptedException is thrown

### ISSUE THREAD

**Issue by scabug** [scala/bug#9554]
scala.concurrent.Future is not completed and onFailure is not called on every case when attached example code is executed. When normal exceptions and "new Error()" is thrown it works as documented, but runs to timeout when OOM / IntEx is thrown. Document clearly states that on IntEx ExectutionException should be the result (and OOM is subclass of Error)

scala.concurrent.Future onFailure document says: 

 The future may contain a throwable object and this means that the future failed. Futures obtained through combinators have the same exception as the future they were obtained from. The following throwable objects are not contained in the future:

    Error - errors are not contained within futures
    InterruptedException - not contained within futures
    all scala.util.control.ControlThrowable except NonLocalReturnControl - not contained within futures

Instead, the future is completed with a ExecutionException with one of the exceptions above as the cause. If a future is failed with a scala.runtime.NonLocalReturnControl, it is completed with a value from that throwable instead.

**Comment by NthPortal** [comment]
This bug does not occur if a `Promise` is completed with a `Failure` containing a fatal `Throwable`; only if a fatal `Throwable` is thrown during execution of a `Future`'s body.

**Comment by NthPortal** [comment]
Looking into this, I've discovered that `CallbackRunnable` does not handle `Throwables` properly. It only handles `NonFatal`s; as it is where all `Future` bodies and callbacks are run, it needs to handle all `Throwable`s.

**Comment by viktorklang** [comment]
@NthPortal Behavior in the face of fatal exception is undefined. Which version are you referring to specifically? And what code are you saying should be handled differently?

**Comment by NthPortal** [comment]
@viktorklang This issue says the problem says that `Future`s are not completed for OOM and `InterruptedException`; in fact, they are not completed for any fatal `Throwable`s.

Currently, the documentation for `onFailure` (soon `onComplete`) states that fatal exceptions/errors get wrapped in `ExecutionException`s. If that is not the case, and their behaviour is meant to be undefined (in this case never completed), then the documentation should be updated to reflect that.

I'm referring to 2.13, though the problem exists for 2.12 as well.

I was referring to [`run` and `executeWithValue`](https://github.com/scala/scala/blob/778b8fdbcedd0b5f3cf4145c7cb5c6a7ddb4106f/src/library/scala/concurrent/impl/Promise.scala#L58-L68) ([here for 2.12](https://github.com/scala/scala/blob/ce95eaf85fb579e392055d95892a491cac540624/src/library/scala/concurrent/impl/Promise.scala#L58-L68)), which only catch `NonFatal`s. Looking more closely, it's actually [`transform`](https://github.com/scala/scala/blob/778b8fdbcedd0b5f3cf4145c7cb5c6a7ddb4106f/src/library/scala/concurrent/impl/Promise.scala#L29) and [`transformWith`](https://github.com/scala/scala/blob/778b8fdbcedd0b5f3cf4145c7cb5c6a7ddb4106f/src/library/scala/concurrent/impl/Promise.scala#L41) which prevent the `Future` from completing (although it would be weird to handle fatals to return them, but not report them in the `ExecutionContext`).

**Comment by viktorklang** [comment]
@NthPortal Where does the docs for the onFailure method say that *fatals* will get wrapped? (I read it a couple of times now but must have missed it or interpreted it differently)

**Comment by NthPortal** [comment]
@viktorklang It doesn't explicitly say all fatals get wrapped, but `InterruptedException` and `ControlThrowable` are both fatal

**Comment by viktorklang** [comment]
@NthPortal Yeah, the docs clearly needs to be more explicit about this. I'll have a look at that as a part of my Futures overhaul.

**Comment by NthPortal** [comment]
@viktorklang Another thing I noticed is that `Promise`s cannot be completed with exceptions that happen in the process of execution, but before (or after, I guess) the body is executed. For example, if `ExecutionContext.execute` throws a `RejectedExecutionException`, the `Promise`/`Future` will never complete, though it should probably fail with said exception.

Personally, I think `Future`s should contain wrapped fatals (otherwise the `Future` never completes, and also the fatal gets ignored), but it's the community's decision how it should behave.

**Comment by viktorklang** [comment]
@NthPortal The first case (REE thrown) is fixed in the overhaul. The second case (auto-wrapping fatals) won't happen. If you want to have fatals propagate, you are free to add such wrapping explicitly (add the fatal as cause to a RuntimeException and throw that)

**Comment by NthPortal** [comment]
@viktorklang Okay, that seems pretty reasonable. I assume they will still get reported though

**Comment by viktorklang** [comment]
@NthPortal I just implemented and verified support for both interruptions and rejections here: https://github.com/viktorklang/scala-futures/commit/2293c15bd9c55968bbb793868564fed9d98db7f1#diff-823e12da79dd0256861a4903168fab59R344

I hope all mods will be ready in time for 2.13 but cannot guarantee it.

**Comment by NthPortal** [comment]
@viktorklang Cheers!

**Comment by viktorklang** [comment]
With the Future code in 2.13.0-M5 InterruptedExceptions should now be correctly handled.
Fatal errors should also be rethrown such that they either surface in the Executor(Service) and can be dealt with there. Keep in mind that all execution after a Fatal Error is undefined.

I'd more than welcome some feedback on the new Future handling here.
